### ISSUE TITLE
go get 报错

### ISSUE THREAD

**Issue by xtgxiso** [satyakb/go-socket.io-redis#2]
go get "github.com/kowabungappl/go-socket.io-redis"
# github.com/kowabungappl/go-socket.io-redis

....\go\src\github.com\kowabungappl\go-socket.io-redis\redis.go:96: cannot use
b (type broadcast) as type socketio.BroadcastAdaptor in return argument:
        broadcast does not implement socketio.BroadcastAdaptor (wrong type for S
end method)
                have Send(socketio.Socket, string, string, []interface {}) error

```
            want Send(socketio.Socket, string, string, ...interface {}) erro
```

r

C:\xtgxiso\source\chat-socket\test>

**Comment by satyakb** [comment]
Thanks, should be fixed now

**Comment by xtgxiso** [comment]
go get github.com/satyakb/go-socket.io-redis 是原来的错误
go get github.com/kowabungappl/go-socket.io-redis 是可以的
