### ISSUE TITLE
Why i always get "concurrent map writes" error using jmeter to presure go-socket.io-redis?

### ISSUE THREAD

**Issue by zackwangwz** [satyakb/go-socket.io-redis#3]
I always get "concurrent map writes" error with the below description:

fatal error: concurrent map writes
goroutine 435 [running]:
runtime.throw(0x900720, 0x15)
    /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8202d30c0 sp=0xc8202d30a8
runtime.mapassign1(0x770940, 0xc82000f9b0, 0xc8202d31c0, 0xc8202d31a0)
    /usr/local/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc8202d3168 sp=0xc8202d30c0
github.com/satyakb/go-socket%2eio-redis.broadcast.Join(0xc82000f590, 0x2d, 0xc820011520, 0x4, 0xc8200bca20, 0x13, 0x7f4e5119c0d0, 0xc82015e000, 0x7f4e5119c0d0, 0xc8200897c0, ...)
    /data/go/dev/src/github.com/satyakb/go-socket.io-redis/redis.go:163 +0x20f fp=0xc8202d31e8 sp=0xc8202d3168
github.com/satyakb/go-socket%2eio-redis.(_broadcast).Join(0xc8200ebc30, 0xc82012e1c0, 0x7, 0x7f4e511e1578, 0xc82020efc0, 0x0, 0x0)
    <autogenerated>:7 +0xfb fp=0xc8202d32c8 sp=0xc8202d31e8
github.com/googollee/go-socket%2eio.(_socketHandler).Join(0xc8202146e0, 0xc82012e0c8, 0x6, 0x0, 0x0)
    /data/go/dev/src/github.com/googollee/go-socket.io/handler.go:91 +0xf0 fp=0xc8202d3358 sp=0xc8202d32c8
main.main.func1.2(0xc8200c09a0, 0xab)
    /data/go/dev/src/gochat/chatapp.go:398 +0x81b fp=0xc8202d35d0 sp=0xc8202d3358
runtime.call32(0xc820693640, 0xc820298b40, 0xc8205800f0, 0x1000000010)
    /usr/local/go/src/runtime/asm_amd64.s:472 +0x3e fp=0xc8202d35f8 sp=0xc8202d35d0
reflect.Value.call(0x77cdc0, 0xc820298b40, 0x13, 0x8ac7a0, 0x4, 0xc82025c920, 0x1, 0x1, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:435 +0x120d fp=0xc8202d3948 sp=0xc8202d35f8
reflect.Value.Call(0x77cdc0, 0xc820298b40, 0x13, 0xc82025c920, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:303 +0xb1 fp=0xc8202d39a8 sp=0xc8202d3948
github.com/googollee/go-socket%2eio.(_caller).Call(0xc820298b80, 0x7f4e511e1578, 0xc82020efc0, 0xc82012e070, 0x1, 0x1, 0x0, 0x0, 0x0)
    /data/go/dev/src/github.com/googollee/go-socket.io/caller.go:81 +0x6c3 fp=0xc8202d3b60 sp=0xc8202d39a8
github.com/googollee/go-socket%2eio.(_socketHandler).onPacket(0xc8202146e0, 0xc8202d3f30, 0xc8202d3ef8, 0x0, 0x0, 0x0, 0x0, 0x0)
    /data/go/dev/src/github.com/googollee/go-socket.io/handler.go:165 +0x37a fp=0xc8202d3d30 sp=0xc8202d3b60
github.com/googollee/go-socket%2eio.(_socket).loop(0xc82020efc0, 0x0, 0x0)
    /data/go/dev/src/github.com/googollee/go-socket.io/socket.go:135 +0x3d3 fp=0xc8202d3f78 sp=0xc8202d3d30
github.com/googollee/go-socket%2eio.(_Server).loop.func1(0xc82020efc0)
    /data/go/dev/src/github.com/googollee/go-socket.io/server.go:103 +0x21 fp=0xc8202d3f98 sp=0xc8202d3f78
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8202d3fa0 sp=0xc8202d3f98
created by github.com/googollee/go-socket%2eio.(*Server).loop
    /data/go/dev/src/github.com/googollee/go-socket.io/server.go:104 +0xfc

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f4e511dcd80, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(_pollDesc).Wait(0xc82017a1b0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0xc82017a1b0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).accept(0xc82017a150, 0x0, 0x7f4e51220d58, 0xc8202066c0)
    /usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(_TCPListener).AcceptTCP(0xc820028098, 0x45cba0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820028098, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(_Server).Serve(0xc820084600, 0x7f4e51220d20, 0xc820028098, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(_Server).ListenAndServe(0xc820084600, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0xc8200115d0, 0x6, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2195 +0x98
main.main()
    /data/go/dev/src/gochat/chatapp.go:561 +0xbe9

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/googollee/go-socket%2eio.(_Server).loop(0xc8200bcb40)
    /data/go/dev/src/github.com/googollee/go-socket.io/server.go:97 +0x6d
created by github.com/googollee/go-socket%2eio.NewServer
    /data/go/dev/src/github.com/googollee/go-socket.io/server.go:26 +0x421
goroutine 362 [select]:
github.com/googollee/go-engine%2eio.(_serverConn).pingLoop(0xc8201e61a0)
    /data/go/dev/src/github.com/googollee/go-engine.io/server_conn.go:359 +0x42f
created by github.com/googollee/go-engine%2eio.newServerConn
    /data/go/dev/src/github.com/googollee/go-engine.io/server_conn.go:110 +0x58e

I tried add lock(sync.RWMutex) for methods: Join/Leave/onmessage/Send, but still get the same error. Could someone give me some helps or ideas? Thanks.

**Comment by satyakb** [comment]
Hey, thanks for submitting the issue. I did some quick research and found the Go's maps are not thread safe. I made a new branch called satya/concurrent_map that uses an implementation of a concurrent map. I don't have jmeter set up yet, so I was wondering if you could try testing this new branch until I get jmeter set up and let me know if this fixes it.

I also would appreciate it if you could provide some details on your jmeter set up so I can replicate the error on my machine.

**Comment by zackwangwz** [comment]
@satyakb Thanks for your quick response, I will try testing the new branch soon and let you know the results.

**Comment by zackwangwz** [comment]
@satyakb I did testing the new branch concurrent_map, still get the same problem, but different error line (/data/go/dev/src/github.com/satyakb/go-socket.io-redis/redis.go:171) as below:

fatal error: concurrent map writes

goroutine 64 [running]:
runtime.throw(0x8f91a0, 0x15)
    /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc82004ba30 sp=0xc82004ba18
runtime.mapdelete(0x76a700, 0xc82101b200, 0xc82004bad0)
    /usr/local/go/src/runtime/hashmap.go:559 +0x5a fp=0xc82004ba90 sp=0xc82004ba30
github.com/satyakb/go-socket%2eio-redis.broadcast.Leave(0xc82000f590, 0x2d, 0xc820011520, 0x4, 0xc8200bca20, 0x13, 0x7fe7ed451280, 0xc82015c0a0, 0x7fe7ed451280, 0xc82015c1e0, ...)
    /data/go/dev/src/github.com/satyakb/go-socket.io-redis/redis.go:171 +0xe6 fp=0xc82004bae8 sp=0xc82004ba90
github.com/satyakb/go-socket%2eio-redis.(_broadcast).Leave(0xc82015c280, 0xc823715fc2, 0x9, 0x7fe7ed496eb0, 0xc820196780, 0x0, 0x0)
    <autogenerated>:3 +0xf9 fp=0xc82004bbc0 sp=0xc82004bae8
github.com/googollee/go-socket%2eio.(_socketHandler).LeaveAll(0xc82014bb20, 0x0, 0x0)
    /data/go/dev/src/github.com/googollee/go-socket.io/handler.go:108 +0x158 fp=0xc82004bcb0 sp=0xc82004bbc0
github.com/googollee/go-socket%2eio.(_socket).loop.func1(0xc820196780)
    /data/go/dev/src/github.com/googollee/go-socket.io/socket.go:112 +0x27 fp=0xc82004bd30 sp=0xc82004bcb0
github.com/googollee/go-socket%2eio.(_socket).loop(0xc820196780, 0x7fe7ed491028, 0xc820010120)
    /data/go/dev/src/github.com/googollee/go-socket.io/socket.go:133 +0x39b fp=0xc82004bf78 sp=0xc82004bd30
github.com/googollee/go-socket%2eio.(_Server).loop.func1(0xc820196780)
    /data/go/dev/src/github.com/googollee/go-socket.io/server.go:103 +0x21 fp=0xc82004bf98 sp=0xc82004bf78
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004bfa0 sp=0xc82004bf98
created by github.com/googollee/go-socket%2eio.(_Server).loop
    /data/go/dev/src/github.com/googollee/go-socket.io/server.go:104 +0xfc

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fe7ed496768, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(_pollDesc).Wait(0xc820160290, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0xc820160290, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).accept(0xc820160230, 0x0, 0x7fe7ed451490, 0xc82423fe20)
    /usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(_TCPListener).AcceptTCP(0xc820162020, 0x459fa0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820162020, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(_Server).Serve(0xc820144200, 0x7fe7ed451458, 0xc820162020, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(_Server).ListenAndServe(0xc820144200, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0xc8200115d0, 0x6, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2195 +0x98
main.main()
    /data/go/dev/src/gochat/chatapp.go:413 +0xb43

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive, 3 minutes]:
github.com/googollee/go-socket%2eio.(*Server).loop(0xc8200bcb40)
    /data/go/dev/src/github.com/googollee/go-socket.io/server.go:97 +0x6d
created by github.com/googollee/go-socket%2eio.NewServer
    /data/go/dev/src/github.com/googollee/go-socket.io/server.go:26 +0x421

goroutine 20 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fe7ed4968e8, 0x72, 0xc820177000)
    /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(_pollDesc).Wait(0xc82013c140, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0xc82013c140, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).Read(0xc82013c0e0, 0xc820177000, 0x1000, 0x1000, 0x0, 0x7fe7ed491050, 0xc8200101b0)
    /usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(_conn).Read(0xc820162010, 0xc820177000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
bufio.(_Reader).fill(0xc82014c1e0)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(_Reader).ReadSlice(0xc82014c1e0, 0x382e7edf00437f0a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:328 +0x21a
github.com/garyburd/redigo/redis.(_conn).readLine(0xc82015c1e0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /data/go/dev/src/github.com/garyburd/redigo/redis/conn.go:338 +0x5a
github.com/garyburd/redigo/redis.(_conn).readReply(0xc82015c1e0, 0x0, 0x0, 0x0, 0x0)
    /data/go/dev/src/github.com/garyburd/redigo/redis/conn.go:411 +0x57
github.com/garyburd/redigo/redis.(*conn).Receive(0xc82015c1e0, 0x0, 0x0, 0x0, 0x0)
    /data/go/dev/src/github.com/garyburd/redigo/redis/conn.go:494 +0x162
github.com/garyburd/redigo/redis.PubSubConn.Receive(0x7fe7ed451280, 0xc82015c1e0, 0x0, 0x0)
    /data/go/dev/src/github.com/garyburd/redigo/redis/pubsub.go:106 +0x5e
github.com/satyakb/go-socket%2eio-redis.Redis.func1(0xc820087860)
    /data/go/dev/src/github.com/satyakb/go-socket.io-redis/redis.go:97 +0x5f
created by github.com/satyakb/go-socket%2eio-redis.Redis
    /data/go/dev/src/github.com/satyakb/go-socket.io-redis/redis.go:113 +0xc4f

goroutine 2267 [select]:
github.com/googollee/go-engine%2eio.(*serverConn).pingLoop(0xc8211b81a0)
    /data/go/dev/src/github.com/googollee/go-engine.io/server_conn.go:359 +0x42f
created by github.com/googollee/go-engine%2eio.newServerConn
    /data/go/dev/src/github.com/googollee/go-engine.io/server_conn.go:110 +0x58e

goroutine 1220 [select]:
github.com/googollee/go-engine%2eio.(*serverConn).pingLoop(0xc820b189c0)
    /data/go/dev/src/github.com/googollee/go-engine.io/server_conn.go:359 +0x42f
created by github.com/googollee/go-engine%2eio.newServerConn
    /data/go/dev/src/github.com/googollee/go-engine.io/server_conn.go:110 +0x58e

goroutine 83 [runnable]:
time.Time.Format(0xece8d8f90, 0xc803be118e, 0xadfa20, 0x915a40, 0x23, 0x0, 0x0)
    /usr/local/go/src/time/format.go:448 +0x136
main.main.func1.6()
    /data/go/dev/src/gochat/chatapp.go:395 +0x299
reflect.Value.call(0x76c400, 0xc820196db0, 0x13, 0x8a5568, 0x4, 0xb03890, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x76c400, 0xc820196db0, 0x13, 0xb03890, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/googollee/go-socket%2eio.(_caller).Call(0xc82014fe40, 0x7fe7ed496eb0, 0xc820196c00, 0xb03890, 0x0, 0x0, 0x0, 0x0, 0x0)
    /data/go/dev/src/github.com/googollee/go-socket.io/caller.go:81 +0x6c3
github.com/googollee/go-socket%2eio.(_socketHandler).onPacket(0xc82014bd80, 0x0, 0xc8201e5cf0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /data/go/dev/src/github.com/googollee/go-socket.io/handler.go:165 +0x37a
github.com/googollee/go-socket%2eio.(_socket).loop.func1(0xc820196c00)
    /data/go/dev/src/github.com/googollee/go-socket.io/socket.go:117 +0x85
github.com/googollee/go-socket%2eio.(_socket).loop(0xc820196c00, 0x7fe7ed491028, 0xc820010120)
    /data/go/dev/src/github.com/googollee/go-socket.io/socket.go:133 +0x39b
github.com/googollee/go-socket%2eio.(_Server).loop.func1(0xc820196c00)
    /data/go/dev/src/github.com/googollee/go-socket.io/server.go:103 +0x21
created by github.com/googollee/go-socket%2eio.(_Server).loop
    /data/go/dev/src/github.com/googollee/go-socket.io/server.go:104 +0xfc

goroutine 48 [select]:
github.com/googollee/go-engine%2eio.(*serverConn).pingLoop(0xc8201d0410)
    /data/go/dev/src/github.com/googollee/go-engine.io/server_conn.go:359 +0x42f
created by github.com/googollee/go-engine%2eio.newServerConn
    /data/go/dev/src/github.com/googollee/go-engine.io/server_conn.go:110 +0x58e

**Comment by zackwangwz** [comment]
@satyakb I added some code that related redis auth, so line 171 should be:
delete(sockets, socket.Id())
in method Leave.

**Comment by satyakb** [comment]
@zackwangwz I made another new branch with some more changes: satya/nested_concurrent_map, can you try with that and let me know? I realized that the map that had issues earlier was a map of maps, so I changed the map to be a concurrent_maps of concurrent_maps.

Also, your line numbers don't seem to line up with mine. Line 171 for me is not in the Leave method, it is in the Send method. However, my Leave method does contain the delete(sockets, socket.Id()) line.

**Comment by zackwangwz** [comment]
@satyakb Great, i did 10 times testing the newest branch, the problem seems to be fixed. But i have another question during testing, i started two processes on one machine using different ports (8080, 8081), it works fine, 8080 messages can be broadcasted to 8081, then I did pressure testing on 8080, after that, 8080 port messages can not be broadcasted to 8081. Am i made some mistakes?
